### ISSUE TITLE
show only matching values

### ISSUE THREAD

**Issue by sant527** [xcash/bootstrap-autocomplete#6]
when i type in the select input it shows all the select items and bolds the matched text. I have to scroll down and check which are the matched ones. Is it possible to show only matched select items.

**Comment by xcash** [comment]
Hi @sant527 
Yes this is by design as the filtering process is in your control. 
This component is designed for dealing with lot of data so the filtering should be don server-side. 
But nothing stops you from filtering yourself implementing your login in the filtering event (the one that normally sends an AJAX request to the server.

**Comment by ecmattos** [comment]
@xcash Could you show me an example ?

**Comment by nidamanx** [comment]
> Hi @sant527 Yes this is by design as the filtering process is in your control. This component is designed for dealing with lot of data so the filtering should be don server-side. But nothing stops you from filtering yourself implementing your login in the filtering event (the one that normally sends an AJAX request to the server.

Sorry to reopen this old post
Any practical example to study on how to show only matching values?
Using Django, I dinamically create server side a json url. I can see all values (almost 40000 records). 
So, a filter will be totally helful, but I tried different ways without luck
Thanks :-)

EDIT:
I forgot to mention I'm using Bootstrap 5.
So, this is the used CDN:
` <script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@xcash-v300/dist/latest/bootstrap-autocomplete.min.js"></script>
`
