### ISSUE TITLE
How can i set URL to .php ?

### ISSUE THREAD

**Issue by playboy58mm** [xcash/bootstrap-autocomplete#66]
i want to use php to generate json data. when i try its cannot work.

**Comment by xcash** [comment]
Please look at the docs.

https://bootstrap-autocomplete.readthedocs.io/en/latest/#basic-usage

**Comment by cchovet** [comment]
Hello Paolo, I'm sorry but I think I have the same problem as OP and the docs didn't seem to help... Duplicating your example page on my server, if in the most basic example I set in resolverSettings "url: 'test-list.json'" all is fine and working as expected. But if I rename the file to test-list.php and change to "url: 'test-list.php'" I get a "TypeError: this.items.forEach is not a function" in "bootstrap-autocomplete.js line 97". And I can't see why the extension of the file would break anything... Having a ".php" file is quite useful because it allows for automatic PHP markup in my editor. Thanks a lot for your insights !

**Comment by playboy58mm** [comment]
you also add datatype parameter to ajax to return json data like this.
> $.ajax({
>     url:"json.php",
>     type: "GET",
>     dataType: "json",
>     success: function(){
>       }
>  });

**Comment by daniol** [comment]
I had the same problem. You have to return the content type json header:

```php
header('Content-Type: application/json');
```
