### ISSUE TITLE
Autocomplete Returns All Items

### ISSUE THREAD

**Issue by bmswens** [xcash/bootstrap-autocomplete#67]
**Is your feature request related to a problem? Please describe.**
As as user, I expect autocomplete forms to filter out and remove anything that doesn't match.
Currently the behavior is to **bold** items that match the query. This can cause and issue when you have 100+ items in a list, but struggle to find which of those items actually match your search. 

**Describe the solution you'd like**
I think that any results that do not match the query should be removed from the display.

**Describe alternatives you've considered**
Tell the users to just look harder.

**Additional context**
I was able to modify the javascript to produce the desired outcome and can submit a pull request if you'd like.

**Current Example**
![image](https://user-images.githubusercontent.com/46857621/82769360-e987be80-9dcf-11ea-8b9a-515b40ae3d7e.png)

**Proposed Solution example**
![image](https://user-images.githubusercontent.com/46857621/82769304-ad545e00-9dcf-11ea-83ff-50cf36a92e78.png)

**Comment by xcash** [comment]
Hi @bmswens 
No, the filtering is up to you. That's because there are two main use cases:
1) small set of static items. You have a static list in your code and you can bypass the ajax call entirely, filtering your items.
2) remote service. You have a server API to filter your results based on the parameters you pass in an ajax call. The server should return only matching items. 

I both cases you should work on the [events.search](https://bootstrap-autocomplete.readthedocs.io/en/latest/#search)  callback.

As every use case is different, this component implements only the basic (and most common) pattern of calling an url passing a `qry` parameter and showing results.

The highlighter (showing matched text in bold) is useful for showing _where_ your typed text is found in that line returned from server.

**Comment by peterVG** [comment]
This was exactly the behaviour I thought autocomplete would provide when I implemented it. I've got a list of hundreds of items I need to filter on. @xcash can you provide an example on how I would use the event.search callback to do that? It's not really clear to me from the documentation. Or @bmswens can you post the PR you were going to submit in a Gist?
