### ISSUE TITLE
Multiple selection support

### ISSUE THREAD

**Issue by weigui008vvv** [xcash/bootstrap-autocomplete#72]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need select multiple options from dropdown list

**Describe the solution you'd like**
Instead of closing dropdown list, select an option will just display value in inputbox and append comma for the next selection from user if "multiple" attr is applied in <select> element

**Describe alternatives you've considered**

**Additional context**

**Comment by xcash** [comment]
Hi @weigui008vvv 

Yes I know what you mean on the multiple selects but I think I'm not going to support it. 
That's because there is not a good way to do it. A way that "fits all". 
When I needed such a feature I always implemented a tag system or other custom styles to fit the  overall UI/UX based on expected number of items selected, what to do when deselecting, etc etc.. 

Btw if more people will ask this I'll re-evaluate. :)

**Comment by xcash** [comment]
Closing for now
