### ISSUE TITLE
Request Throttling not working with custom resolver

### ISSUE THREAD

**Issue by kAvItHa-cL** [xcash/bootstrap-autocomplete#78]
Hi,
I am using 
resolver:'custom',
resolverSettings:{ requestthrottling: 2000}
//custom ajax call

but delay on request not working, is there a way to achieve it?

**Comment by xcash** [comment]
Hi @kAvItHa-cL 

This is by design. When using a custom resolver there are no certain ways to block a request as the resolver is completely obscure from the component point of view.

If you're using a basic Ajax call you could implement the same logic i use for the basicresolver.
I keep a class global storing the last timeoutID I issue when launching the search event. 
If that value is not null I cancel it to stop the execution of the ajax request.
This is the relevant code

```
    [...]
    // request throttling
    if (this.requestTID) {
      window.clearTimeout(this.requestTID);
    }
    this.requestTID = window.setTimeout(() => {
      this.jqXHR = $.ajax(
        this._settings.url,
        {
          method: this._settings.method,
          data,
          timeout: this._settings.timeout
        }
      );
    [...]
```

Feel free to peek at the code here -> https://github.com/xcash/bootstrap-autocomplete/blob/master/src/resolvers.ts#L58
