### ISSUE TITLE
Hide item if not match

### ISSUE THREAD

**Issue by kiznick** [xcash/bootstrap-autocomplete#96]
Hide item if not match

I use static json file and want to hide item if not match
![image](https://user-images.githubusercontent.com/22832362/100440205-1f876180-30d7-11eb-9523-b015909c1ce4.png)

Thanks.

**Comment by sinag** [comment]
I am also looking for this

**Comment by xcash** [comment]
This library was created for server backed autocomplete. 
If you want to perform the lookup locally you need to implement a custom `search` event. 

And, since you are using a local json file, you shouldn't download it every lookup.
So imagine you've loaded the json dataset in some way and you have a global/local variable you could write something like:

```
var mydataset = { 'key`: `value` };

$('.advancedAutoComplete').autoComplete({
    resolver: 'custom',
    events: {
        search: function (qry, callback) {
         let results = mydataset.filter( (e) => { return e.value.indexOf(qry) > -1 } );
         callback(results);
        }
    }
});
```

The above is **NOT TESTED**. Just some pseudo code to explain the methodology. :)
